<?php
$collection = $block->getTicket()
    ->setOrder('last_reply_at', 'desc');
$count       = $collection->count();
$size        = $collection->getSize();
$limit       = $block->getLimit();
$currentPage = $block->getCurrentPage();
$start       = $size - (($currentPage - 1) * $limit);
$modId       = time() . rand();
$helper = $this->helper("Lof\HelpDesk\Helper\Data");
?>
<?php if($count): ?>
<div class="block lrw-block lrw-account-summary-listing">
	<div class="block-content">
		<div class="table-wrapper orders-recent">
			<table class="data-table table">
				<thead>
					<tr>
						<th><?= __('Ticket ID'); ?></th>
						<th><?= __('Subject'); ?></th>
						<th><?= __('Category'); ?></th>
						<th><?= __('Last Activity'); ?></th>
						<th><?= __('Status'); ?></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<?php $i = 0; ?>
					<?php foreach ($collection as $_ticket): ?>
					<?php $amount = $_ticket->getAmount(); ?>
					<tr class="<?= $i % 2 ? 'odd' : 'even' ?> <?= ($i == $count-1) ? 'last' : '' ?>">
						<td><?= $_ticket->getId(); ?></td>
						<td><a class="box-body" href="<?= $block->getUrl('lofhelpdesk/ticket/view', ['ticket_id' => $_ticket->getData('ticket_id')]); ?>"><?= $_ticket->getSubject() ?></a></td>
						<td><?= $this->getCategoryName($_ticket->getCategoryId()); ?>
						</td>
						<td><?= $_ticket->getLastReplyAt(); ?></td>
						<td class="lrw-status-<?= str_replace(" ", "-", strtolower($this->getStatus($_ticket->getStatusId()))); ?>">
							<?= $this->getStatus($_ticket->getStatusId()); ?>
						</td>
						<td>
							<?php  if($this->getUnreadMessageCount($_ticket->getData('ticket_id')) >0 ): ?><i class="fa fa-circle unread" aria-hidden="true"></i>
							<?php else: ?>
							<i class="fa fa-circle" aria-hidden="true"></i>
							<?php endif; ?>
						</td>
					</tr>
					<?php $i++; ?>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
		<?= $block->getChildHtml('toolbar'); ?>
	</div>
</div>

<?php endif; ?>
<div class="block lrw-block lrw-account-summary-listing">
	<div class="block-title">
		<strong><?= __('Create New Ticket');?></strong>
	</div>
	<div class="block-content">
		<div class="orders-recent">
			<div id="lofform<?= $modId;?>" class="helpdesk-form">
				<div class="form-content">
					<form id="helpdesk<?= $modId;?>" class="helpdesk form" action="<?php  echo $block->getUrl('*/*/saveticket')?>" method="post" data-hasrequired="<?= __('* Required Fields') ?>" data-mage-init='{"validation":{}}' enctype="multipart/form-data">
						<div class="form-list row">
							<div class="field col-sm-6">
								<div class="response-field-text">
									<div class="subtemplate-wrapper">
										<label for="subject" class="required"><?= __('Subject'); ?><em>*</em>
										</label>
										<div class="row">
											<div class="col-sm-12">
												<div class="subtemplate-inner">
													<input name="subject" id="subject" title="Subject" value="" class="input-text required-entry _required" type="text">
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="field col-sm-3">
								<div class="response-field-text">
									<div class="subtemplate-wrapper">
										<label for="category_id" class="required"><?= __('Category'); ?><em>*</em>
										</label>
										<div class="row">
											<div class="col-sm-12">
												<div class="subtemplate-inner">
													<select id="category_id" name="category_id" class="form-control select2 required-entry" style="width: 100%;">
														<option value><?= __('Select a category'); ?></option>
								                  		<?php
								                  		foreach ($block->getCategory() as $key => $category):
                                                            $category->load($category->getId());
									                  		if(in_array($helper->getStoreId(), $category->getStoreId()) || in_array(0, $category->getStoreId())):
									                  			?>

										                  		<option value="<?= $category->getData('category_id'); ?>"><?= $category->getData('title'); ?></option>
										                  		<?php
															endif;
										                endforeach; ?>
								                	</select>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="field col-sm-3">
								<div class="response-field-text">
									<div class="subtemplate-wrapper">
										<label for="priority_id" class="required"><?= __('Priority'); ?><em>*</em>
										</label>
										<div class="row">
											<div class="col-sm-12">
												<div class="subtemplate-inner">
													<select id="priority_id" name="priority_id" class="form-control select2 required-entry" style="width: 100%;">
														<option value><?= __('Select a priority'); ?></option>
								                  		<?php foreach ($block->getPriority() as $key => $priority): ?>
								                  		<option value="<?= $priority['id']; ?>"><?= $priority['title']; ?></option>
								                  		<?php endforeach; ?>
								                	</select>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="field col-sm-12">
								<div class="response-field-text">
									<div class="subtemplate-wrapper">
										<label for="description " class="required"><?= __('Message '); ?><em>*</em>
										</label>
										<div class="row">
											<div class="col-sm-12">
												<div class="subtemplate-inner">
													<textarea name="description" id="description" class="input-text required-entry _required" rows="5" aria-required="true"></textarea>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="field col-sm-12 ">
								<div class="response-field-file_upload">
									<div class="subtemplate-wrapper">
										<label for="attachment" class="required"><?= __('Attachment (Up to 2.0 MB per image.Acceptable image formats: jpg, jpeg, png)');?></label>
										<div class="input-box">
											<input name="attachment" id="attachment" title="Attachment" class="input-text validate-filesize validate-fileextensions" type="file">
										</div>
									</div>
								</div>
							</div>
							<?php if(count($block->getOrder()) > 0): ?>
							<div class="field col-sm-6">
								<div class="response-field-text">
									<div class="subtemplate-wrapper">
										<label for="order_id" class="required"><?= __('Order'); ?><em>*</em>
										</label>
										<div class="row">
											<div class="col-sm-12">
												<div class="subtemplate-inner">
													<select id="order_id" name="order_id" class="form-control select2 required-entry">
													<option value><?= __('Select an order'); ?></option>
							                  		<?php foreach ($block->getOrder() as $key => $order): ?>
							                  		<option value="<?= $order['id']; ?>"><?= $order['name']; ?></option>
							                  		<?php endforeach; ?>
								                	</select>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="field col-sm-6">
								<div class="response-field-text">
									<div class="subtemplate-wrapper">
										<label for="product_id" class="required"><?= __('Product'); ?><em>*</em>
										</label>
										<div class="row">
											<div class="col-sm-12">
												<div class="subtemplate-inner">
													<select multiple id="product_id" name="products[]" class="form-control multiple  required-entry _required">

							                  		<?php foreach ($block->getProduct() as $key => $product) { ?>
							                  		<option value="<?= $product['value']; ?>" data-order-id="<?= $product['order_id']; ?>" style="display: none;"><?= $product['label']; ?></option>
							                  		<?php } ?>
								                	</select>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="field col-sm-6">
								<div class="response-field-text">
									<div class="subtemplate-wrapper">
										<label for="qty_requested"><?= __('Request QTY'); ?></label>
										<div class="row">
											<div class="col-sm-12">
												<div class="subtemplate-inner">
													<select id="qty_requested" name="qty_requested" class="form-control">
							                  		<?php foreach ($block->getProduct() as $key => $product): ?>
														<?php for ($i = 0; $i <= (int)$product['qty']; $i++){ ?>
															<option data-maxvalue="<?= $product['qty']; ?>" value="<?= $i; ?>" data-order-id="<?= $product['order_id']; ?>" data-product-id="<?= $product['value']; ?>" style="display: none;"><?= $i; ?></option>
														<?php } ?>
														<?php endforeach; ?>
								                	</select>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							<?php endif; ?>
						</div>
						<div class="row">
							<div class="buttons-set col-sm-12">
							<button type="submit" title="Submit" class="formbuilder-button button action-primary">
								<span>
									<?= __('Submit Ticket'); ?>
								</span>
							</button>
						</div>
					</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	require([
        'jquery',
        'jquery/ui',
        'jquery/validate',
        'mage/translate'
    ], function ($) {
    $( "#order_id" ).change(function () {
    	var order_id = $(this).val();
    	$('#product_id option').each(function(){
	    	if($(this).data('orderId') == order_id) {
	    		$('#product_id option').css('display','none');
	    		$(this).css('display','block');
	    	}
	    });
  	});
	$('#product_id').change(function () {
		var product_id = $(this).val();
		var order_id = $( "#order_id" ).val();
		$('#qty_requested option').each(function(){
	    	if($(this).data('productId') == product_id && $(this).data('orderId') == order_id) {
	    		$('#qty_requested option').css('display','none');
	    		$(this).css('display','block');
	    	}
	    });
	})
    //Validate Image FileSize

    $.validator.addMethod(
            'validate-filesize', function (v, elm) {
                var maxSize = 2 * 102400;
                if (navigator.appName == "Microsoft Internet Explorer") {
                    if (elm.value) {
                        var oas = new ActiveXObject("Scripting.FileSystemObject");
                        var e = oas.getFile(elm.value);
                        var size = e.size;
                    }
                } else {
                    if (elm.files[0] != undefined) {
                        size = elm.files[0].size;
                    }
                }
                if (size != undefined && size > maxSize) {
                    return false;
                }
                return true;
            }, $.mage.__('The file size should not exceed 2MB'));

    //Validate Image Extensions

    $.validator.addMethod(
            'validate-fileextensions', function (v, elm) {

                var extensions = ['jpeg', 'jpg', 'png', 'gif'];
                if (!v) {
                    return true;
                }
                with (elm) {
                    var ext = value.substring(value.lastIndexOf('.') + 1);
                    for (i = 0; i < extensions.length; i++) {
                        if (ext == extensions[i]) {
                            return true;
                        }
                    }
                }
                return false;
            }, $.mage.__('Disallowed file type.'));

    //Validate Image Width and Height

    $.validator.addMethod(
            'validate-image-height-width', function (v, elm) {

                if (!v) {
                    return true;
                }
                with (elm) {
                    var file, img;
                    if ((file = elm.files[0])) {
                        img = new Image();
                        img.onload = function () {
                            var height = this.height,
                                    width = this.width;
                            if (height > 100 || width > 100) {
                                return false;
                            }

                            return true;
                        };
                    }
                }
                return false;
            }, $.mage.__('Height and Width must not exceed 100px.'));
});
</script>
